apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: enjoy-back-deploy
spec:
  selector:
    matchLabels:
      app: enjoy-back
  template:
    metadata:
      name: enjoy-back-pod
      labels:
        app: enjoy-back
    spec:
      containers:
        - name: enjoy-back-container
          image: 255260635764.dkr.ecr.ap-northeast-2.amazonaws.com/enjoy-back:20250922-021844
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: enjoy-db-secret
                  key: DB_URL
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: enjoy-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: enjoy-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 300Mi
            limits:
              cpu: 400m
              memory: 300Mi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: enjoy-back
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: enjoy-back
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: enjoy-back
  strategy:
    canary:
      steps:
        - setWeight: 25
        - pause: { duration: 10 }
        - setWeight: 50
        - pause: { duration: 10 }
        - setWeight: 100
