apiVersion: v1
kind: Secret
metadata:
  name: enjoy-db-secret
type: Opaque
data:
  DB_HOST: ZW5qb3ktZGIuY2JncTRhNDB1djJrLmFwLW5vcnRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29t
  DB_URL: amRiYzpteXNxbDovL2Vuam95LWRiLmNiZ3E0YTQwdXYyay5hcC1ub3J0aGVhc3QtMi5yZHMuYW1hem9uYXdzLmNvbS9lbmpveXRyaXA=
  DB_USERNAME: ZW5qb3lkYg==
  DB_PASSWORD: ZW50MTIzNDU=
