apiVersion: apps/v1
kind: Deployment
metadata:
  name: enjoy-back-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enjoy-back
  template:
    metadata:
      name: enjoy-back-pod
      labels:
        app: enjoy-back
    spec:
      containers:
        - name: enjoy-back-container
          image: 255260635764.dkr.ecr.ap-northeast-2.amazonaws.com/enjoy-back:20250918-085032
          env:
            - name: DB_URL
              #value: "jdbc:mysql://enjoy-db.cbgq4a40uv2k.ap-northeast-2.rds.amazonaws.com/enjoytrip"
              valueFrom:
                secretKeyRef:
                  name: enjoy-db-secret
                  key: DB_URL
            - name: DB_USERNAME
              # value: "enjoydb"
              valueFrom:
                secretKeyRef:
                  name: enjoy-db-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              #value: "ent12345"
              valueFrom:
                secretKeyRef:
                  name: enjoy-db-secret
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: 200m
              memory: 500Mi
            limits:
              cpu: 200m
              memory: 500Mi
