apiVersion: v1
kind: Secret
metadata:
  name: enjoy-db-secret
type: Opaque
data:
  DB_HOST: bXlkYi5jNXF5YW9veTgwdXAuYXAtbm9ydGhlYXN0LTIucmRzLmFtYXpvbmF3cy5jb20=
  DB_URL: amRiYzpteXNxbDovL215ZGIuYzVxeWFvb3k4MHVwLmFwLW5vcnRoZWFzdC0yLnJkcy5hbWF6b25hd3MuY29tL215ZGI=
  DB_USERNAME: YWRtaW4=
  DB_PASSWORD: cG93ZXJtdnA=
